config/routes.rb
Superkuku::Application.routes.draw do
  resources :search_suggestions

  resources :posts

  devise_for :users
  get 'about' => 'pages#about'
  
  root 'posts#index'
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :description, presence: true, length: { maximum: 300 }

	belongs_to :user
	validates :user_id, presence: true

	has_attached_file :image, styles: { thumb: "100x100>"}
	validates_attachment :image,
												content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
												size: { less_than: 5.megabytes }

	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super
		# super make sure that any functionality that already define also will happen
	end

	def self.search(search)
  if search
    where('description LIKE ?', "%#{search}%")
  else
    scoped
  end
end

end

app/models/search_suggestion.rb
class SearchSuggestion
	def self.terms_for(prefix)
		$redis.zrevrange "search-suggestions:#{prefix.downcase}", 0, 9
	end

	def self.index_posts
		Post.find_each do |post|
			index_term(post.description)
			post.description.split.each { |t| index_term(t) }
		end
	end

	def self.index_term(term)
		1.upto(term.length-1) do |n|
			prefix = term[0, n]
			$redis.zincrby "search-suggestions:#{prefix.downcase}", 1, term.downcase
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :miniprofiler
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  private
  def miniprofiler
    # required only in production
    #if is_admin?
      Rack::MiniProfiler.authorize_request
    #end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
  end

  def show_video(url)
    render :partial => 'shared/video', :locals => { :url => url }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # Must authenticate user first before actions except index action.
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts= Post.search(params[:search]).order("created_at desc").page(params[:page]).per_page(20)

    #@posts = Post.q(params[:q])
    #@posts = Post.order("created_at desc").page(params[:page]).per_page(20)
    #@posts = Post.all
    #to show only current_user Posts
    #@posts = current_user.posts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json {render json: @posts}
      format.js #index.js.erb
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
    #@post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    #@post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = current_user.posts.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # This is the Rails 4 strong parameters instead of Rails 3 attributes_accessible
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image, :image_remote_url, :video_remote_url)
    end
end

app/controllers/search_suggestions_controller.rb
class SearchSuggestionsController < ApplicationController
  def index
    render json: SearchSuggestion.terms_for(params[:term])
    #render json: %w[foo bar]
  end

 	# Never trust parameters from the scary internet, only allow the white list through.
  #def post_params
  #  params.require(:search_suggestion).permit(:popularity, :item)
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def youtube_embed(youtube_url)
	  if youtube_url[/youtu\.be\/([^\?]*)/]
	    youtube_id = $1
	  else
	    # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
	    youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
	    youtube_id = $5
	  end

  	%Q{<iframe title="YouTube video player" width="320" height="216" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		&copy; 2013 SUPERKUKU.COM
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
    <%= link_to image_tag("logo.png", :border => 0, :alt => 'SUPERKUKU'), root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
      <div class="row">
        <div class="span9"></div>
      </div>
      <div class="row">
        <div class="span4 offset3">
          <%- #tag is use for more generic ones. w/o is for model attributes -%>
          <%= form_tag posts_path, method: 'get' do %>
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search", :name => nil ) %>
          <% end %>
        </div>
        <div class="span2">
          <%= link_to 'Lodge a driver', new_post_path, class: "btn btn-danger" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SUPERKUKU</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		
		<div class="container">
      <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>

	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
	<h1>Welcome.</h1>
	<h4>Please share a new post or leave some constructive comments behind. Thanks.</h4>
<% else %>
<%-# unless user_signed_in? -%>
	<div>
		<h1>Log bad driving and other traffic nonsense</h1>
		<p>
			Have you seen any ridiculous drivers out there? With the aim to raise road awareness and hopefully build a more considerate community, this site curates all the bad driving, hoping road users can learn NOT to make the same mistakes.  
		</p>
		<p>
			<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary" %>
		</p>
	</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
	<p>
		<%= link_to "SUPERKUKU.COM", "http://superkuku.com" %>
		aim to raise road awareness and hopefully build a more considerate road community by curating all the bad driving in the hope of motorists NOT making the same mistakes. Or it's bad driving just for laughs, or shame.
	</p>
		
	<p> Regardless, let's all look at the world a little differently. Love everyone, even with the mistakes they made. And hope from there, they can change. Together we can change the world, one at a time.
	</p>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
  <%= f.input :image_remote_url, label: "Or enter a image URL" %>
  <%= f.input :video_remote_url, label: "Or enter a video URL" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="box">
	<%- # link_to (image_tag post.image(:thumb)), post -%>
	<% if post.image.blank? %>
		<div class="video">
			<%= raw(youtube_embed(post.video_remote_url)) %>
		</div>
	<% else %>
		<%= link_to (image_tag post.image), post %>
	<% end %>
	<div class="description">
		"<%= post.description %>"
	</div>
	<div class="aside">
		Posted by <%= post.user.name %>
	
		<% if current_user == post.user %>
			<%= link_to 'Edit', edit_post_path(post) %>
			<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
		
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'pages/home' %>
<div id="posts">
  <%= render @posts %>
</div>

<%= will_paginate @posts %>

<%-# link_to 'New Post', new_post_path -%>

app/views/posts/index.js.erb
$boxes = $('<%= j render(@posts) %>')


$('#posts').append( $boxes ).isotope( 'appended', $boxes).imagesLoaded( function(){
  $('#posts').isotope( 'reLayout');
});

<% if @posts.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
	$('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @post.image %>
			<p>
		  	<%= @post.description %>
			</p>
			<p>
		  	<%= @post.user.name%> | <%= @post.created_at %>
			</p>
			<% if current_user == @post.user %>
				<%= link_to 'Edit', edit_post_path(@post) %> |
			<% end %>	
			<%= link_to 'Back', posts_path %>
			
		</div>
	</div>
</div>